export const THEMES = {
  existencialismo: { label: "Existencialismo", color: "#8B5CF6" },
  redencion: { label: "Redención", color: "#F59E0B" },
  fe: { label: "Fe y moralidad", color: "#3B82F6" },
  amor: { label: "Amor", color: "#EC4899" },
  sociedad: { label: "Sociedad", color: "#10B981" },
  psicologia: { label: "Psicología", color: "#EF4444" },
  politica: { label: "Política", color: "#6366F1" },
  familia: { label: "Familia", color: "#F97316" },
  identidad: { label: "Identidad", color: "#14B8A6" },
  crimen: { label: "Crimen", color: "#DC2626" },
  soledad: { label: "Soledad", color: "#6B7280" },
  adiccion: { label: "Adicción", color: "#A855F7" },
};

export const NOVELS = [
  {
    id: "pobres-gentes",
    title: "Pobres gentes",
    titleOrig: "Бедные люди",
    year: 1846,
    pages: 180,
    chapters: 31,
    themes: ["amor", "sociedad", "soledad"],
    desc: "Intercambio epistolar entre un funcionario humilde y una joven costurera que revela la dignidad en la pobreza.",
    cover: "letter",
    location: "San Petersburgo, Rusia",
    writtenContext: "Primera novela de Dostoievski, escrita a los 24 años. Bélinskiy, el crítico más influyente de la época, la elogió diciendo: «¡Ha nacido un nuevo Gógol!». Publicada en 1846 en el Almanaque de Petersburgo.",
    characters: [
      { name: "Makar Dévushkin", desc: "Funcionario copista empobrecido, bondadoso y sentimental" },
      { name: "Várvara Dobrosiólova", desc: "Joven huérfana y costurera, corresponsal de Makar" },
      { name: "Bykov", desc: "Terrateniente adinerado que se casa con Várara por conveniencia" },
    ],
    relationships: [
      { from: 0, to: 1, type: "amor-no-correspondido", label: "amor epistolar" },
      { from: 2, to: 1, type: "manipulacion", label: "matrimonio forzado" },
    ],
  },
  {
    id: "el-doble",
    title: "El doble",
    titleOrig: "Двойник",
    year: 1846,
    pages: 140,
    chapters: 13,
    themes: ["identidad", "psicologia"],
    desc: "Un burócrata descubre que un doble idéntico invade su vida, precipitándolo hacia la locura.",
    cover: "double",
    location: "San Petersburgo, Rusia",
    writtenContext: "Segunda novela, publicada apenas semanas después de Pobres gentes en 1846. Fue mal recibida por la crítica. Dostoievski la consideraba una de sus ideas más importantes, aunque reconocía que la forma había fallado.",
    characters: [
      { name: "Yákov Petróvich Goliadkin", desc: "Consejero titular inseguro y paranoico, protagonista" },
      { name: "Goliadkin Jr.", desc: "El doble idéntico, astuto y manipulador, que usurpa su vida" },
      { name: "Klara Olsúfievna", desc: "Hija del consejero de Estado, objeto del amor imposible de Goliadkin" },
    ],
    relationships: [
      { from: 0, to: 1, type: "rivalidad", label: "doble usurpador" },
      { from: 0, to: 2, type: "amor-no-correspondido", label: "amor imposible" },
      { from: 1, to: 2, type: "rivalidad", label: "pretende a Klara" },
    ],
  },
  {
    id: "noches-blancas",
    title: "Noches blancas",
    titleOrig: "Белые ночи",
    year: 1848,
    pages: 80,
    chapters: 6,
    themes: ["amor", "soledad"],
    desc: "Cuatro noches de encuentro entre un soñador solitario y una joven que espera a su amado en San Petersburgo.",
    cover: "moon",
    location: "San Petersburgo, Rusia",
    writtenContext: "Escrita en 1848, poco antes del arresto de Dostoievski por participar en el círculo Petrashevski. Ambientada durante las célebres noches blancas de San Petersburgo, cuando el sol apenas se oculta.",
    characters: [
      { name: "El Soñador", desc: "Narrador anónimo, joven solitario e idealista que vive en sus fantasías" },
      { name: "Nástenka", desc: "Joven vivaz que espera el regreso de su amado junto al canal" },
      { name: "El inquilino", desc: "Amado ausente de Nástenka que regresa al final" },
    ],
    relationships: [
      { from: 0, to: 1, type: "amor-no-correspondido", label: "se enamora de" },
      { from: 1, to: 2, type: "amor", label: "amado ausente" },
    ],
  },
  {
    id: "humillados-y-ofendidos",
    title: "Humillados y ofendidos",
    titleOrig: "Униженные и оскорблённые",
    year: 1861,
    pages: 350,
    chapters: 45,
    themes: ["sociedad", "amor", "redencion"],
    desc: "Un escritor enfermo narra la destrucción de familias enteras por la crueldad de un aristócrata sin escrúpulos.",
    cover: "broken",
    location: "San Petersburgo, Rusia",
    writtenContext: "Primera novela tras regresar del exilio en Siberia (1849-1859). Publicada por entregas en la revista Tiempo, que Dostoievski cofundó con su hermano Mijaíl. Marca su regreso a la vida literaria petersburguesa.",
    characters: [
      { name: "Iván Petróvich", desc: "Escritor y narrador, enamorado de Natasha" },
      { name: "Natasha Ihmenieva", desc: "Joven que abandona a su familia por amor a Aliosha" },
      { name: "Príncipe Valkovski", desc: "Aristócrata cínico y despiadado, antagonista principal" },
      { name: "Aliosha (Alexéi)", desc: "Hijo del príncipe, ingenuo y voluble en sus afectos" },
      { name: "Nelly", desc: "Niña huérfana y enferma, víctima de la crueldad de Valkovski" },
    ],
    relationships: [
      { from: 0, to: 1, type: "amor-no-correspondido", label: "enamorado de" },
      { from: 1, to: 3, type: "amor", label: "abandona familia por" },
      { from: 2, to: 3, type: "familia", label: "padre e hijo" },
      { from: 2, to: 4, type: "manipulacion", label: "victimario" },
      { from: 2, to: 1, type: "manipulacion", label: "intenta separar" },
    ],
  },
  {
    id: "memorias-del-subsuelo",
    title: "Memorias del subsuelo",
    titleOrig: "Записки из подполья",
    year: 1864,
    pages: 130,
    chapters: 11,
    themes: ["existencialismo", "psicologia", "soledad"],
    desc: "El monólogo frenético de un hombre que rechaza la razón y la sociedad desde su agujero subterráneo.",
    cover: "stairs",
    location: "San Petersburgo, Rusia",
    writtenContext: "Escrita en 1864, año trágico para Dostoievski: murieron su esposa María y su hermano Mijaíl. Considerada precursora del existencialismo, fue una respuesta directa al racionalismo utópico de Chernishevski.",
    characters: [
      { name: "El Hombre del Subsuelo", desc: "Narrador anónimo, exfuncionario amargado y contradictorio de 40 años" },
      { name: "Liza", desc: "Joven prostituta a quien el narrador intenta redimir y luego humilla" },
      { name: "Zvérkov", desc: "Antiguo compañero de escuela, exitoso y arrogante, objeto de la envidia del narrador" },
    ],
    relationships: [
      { from: 0, to: 1, type: "manipulacion", label: "humilla e intenta redimir" },
      { from: 0, to: 2, type: "rivalidad", label: "envidia y resentimiento" },
    ],
  },
  {
    id: "crimen-y-castigo",
    title: "Crimen y castigo",
    titleOrig: "Преступление и наказание",
    year: 1866,
    pages: 580,
    chapters: 42,
    themes: ["crimen", "redencion", "psicologia", "fe"],
    desc: "Un estudiante asesina a una anciana usuraria convencido de su superioridad moral, pero la culpa lo consume.",
    cover: "axe",
    location: "San Petersburgo, Rusia",
    writtenContext: "Escrita entre 1865-1866, publicada por entregas en El Mensajero Ruso. Dostoievski la escribió bajo enorme presión económica, agobiado por deudas de juego y las de la revista de su difunto hermano.",
    characters: [
      { name: "Rodión Raskólnikov", desc: "Estudiante empobrecido que planea y comete un doble asesinato" },
      { name: "Sonia Marmeládova", desc: "Joven que se sacrifica por su familia, guía moral de Raskólnikov" },
      { name: "Porfirio Petróvich", desc: "Juez de instrucción astuto que investiga el crimen" },
      { name: "Dunia Raskólnikova", desc: "Hermana de Rodión, fuerte e independiente" },
      { name: "Svidrigáilov", desc: "Terrateniente corrupto y nihilista obsesionado con Dunia" },
    ],
    relationships: [
      { from: 0, to: 1, type: "amor", label: "redención mutua" },
      { from: 0, to: 3, type: "familia", label: "hermanos" },
      { from: 2, to: 0, type: "investigacion", label: "investiga" },
      { from: 4, to: 3, type: "amor-no-correspondido", label: "obsesión" },
      { from: 4, to: 0, type: "rivalidad", label: "doble oscuro" },
    ],
  },
  {
    id: "el-jugador",
    title: "El jugador",
    titleOrig: "Игрок",
    year: 1867,
    pages: 170,
    chapters: 17,
    themes: ["adiccion", "amor", "sociedad"],
    desc: "Un tutor ruso se hunde en la fiebre de la ruleta en un casino alemán, atrapado entre el juego y una mujer.",
    cover: "roulette",
    location: "Roulettenburg (ciudad ficticia alemana, inspirada en Wiesbaden y Bad Homburg)",
    writtenContext: "Dictada en solo 26 días a la taquígrafa Anna Grigórievna Snítkina (su futura segunda esposa) para cumplir un contrato editorial leonino. Basada en su propia adicción al juego en los casinos europeos.",
    characters: [
      { name: "Alexéi Ivánovich", desc: "Tutor ruso, narrador, atrapado por la adicción al juego" },
      { name: "Polina", desc: "Hijastra del General, mujer orgullosa de quien Alexéi está enamorado" },
      { name: "El General", desc: "Militar retirado endeudado que espera la herencia de su tía" },
      { name: "La Abuelita (Antonida Vasílievna)", desc: "Anciana rica que llega al casino y pierde una fortuna en la ruleta" },
      { name: "Mr. Astley", desc: "Inglés reservado y honorable, enamorado en secreto de Polina" },
    ],
    relationships: [
      { from: 0, to: 1, type: "amor-no-correspondido", label: "enamorado de" },
      { from: 2, to: 1, type: "familia", label: "padrastro" },
      { from: 2, to: 3, type: "familia", label: "espera herencia" },
      { from: 4, to: 1, type: "amor-no-correspondido", label: "amor secreto" },
    ],
  },
  {
    id: "el-idiota",
    title: "El idiota",
    titleOrig: "Идиот",
    year: 1869,
    pages: 640,
    chapters: 44,
    themes: ["fe", "sociedad", "amor", "psicologia"],
    desc: "El príncipe Myshkin, un hombre de bondad cristiana absoluta, es destruido por la sociedad petersburguesa.",
    cover: "halo",
    location: "San Petersburgo y Pávlovsk, Rusia (con prólogo en Suiza)",
    writtenContext: "Escrita entre 1867-1869 durante el primer viaje al extranjero de Dostoievski con su esposa Anna. Compuesta entre Ginebra, Vevey, Milán y Florencia, mientras el matrimonio vivía en la pobreza.",
    characters: [
      { name: "Príncipe Lev Myshkin", desc: "Hombre de bondad pura, epiléptico, recién regresado de un sanatorio suizo" },
      { name: "Nastasia Filíppovna", desc: "Mujer de belleza trágica, atormentada por su pasado de abuso" },
      { name: "Parfión Rogozhin", desc: "Hijo de comerciante, apasionado y violento, obsesionado con Nastasia" },
      { name: "Aglaya Yepánchina", desc: "Joven inteligente y orgullosa, enamorada del príncipe" },
      { name: "Gania Ivolguin", desc: "Secretario ambicioso que busca casarse por dinero" },
    ],
    relationships: [
      { from: 0, to: 1, type: "amor", label: "compasión y amor" },
      { from: 0, to: 3, type: "amor", label: "amor puro" },
      { from: 2, to: 1, type: "amor", label: "obsesión posesiva" },
      { from: 2, to: 0, type: "rivalidad", label: "rival y hermano jurado" },
      { from: 4, to: 1, type: "manipulacion", label: "pretende por dinero" },
    ],
  },
  {
    id: "el-eterno-marido",
    title: "El eterno marido",
    titleOrig: "Вечный муж",
    year: 1870,
    pages: 160,
    chapters: 17,
    themes: ["psicologia", "identidad"],
    desc: "Un viudo busca al amante de su esposa fallecida en un duelo psicológico de humillación y dependencia.",
    cover: "ring",
    location: "San Petersburgo, Rusia",
    writtenContext: "Novela corta escrita en 1870, durante el período más productivo de Dostoievski en el extranjero. Publicada en la revista Aurora. Una de sus obras más concentradas y psicológicamente incisivas.",
    characters: [
      { name: "Pável Pávlovich Trúsotski", desc: "Viudo sumiso que busca al amante de su difunta esposa" },
      { name: "Alexéi Ivánovich Velchanínov", desc: "Ex amante elegante y ocioso, atormentado por la culpa" },
      { name: "Liza", desc: "Hija de la difunta esposa, posiblemente hija biológica de Velchanínov" },
    ],
    relationships: [
      { from: 0, to: 1, type: "rivalidad", label: "busca al amante" },
      { from: 1, to: 2, type: "familia", label: "posible padre" },
      { from: 0, to: 2, type: "familia", label: "padre legal" },
    ],
  },
  {
    id: "los-demonios",
    title: "Los demonios",
    titleOrig: "Бесы",
    year: 1872,
    pages: 700,
    chapters: 38,
    themes: ["politica", "existencialismo", "crimen"],
    desc: "Una célula revolucionaria nihilista siembra el caos en una ciudad provinciana rusa, destruyendo todo a su paso.",
    cover: "flame",
    location: "Ciudad provinciana ficticia, Rusia",
    writtenContext: "Inspirada en el caso real de Necháiev, revolucionario que ordenó el asesinato de un miembro de su propia célula en 1869. Dostoievski la escribió como advertencia profética contra el nihilismo radical.",
    characters: [
      { name: "Nikolái Stavroguin", desc: "Carismático y enigmático, centro moral vacío de la novela" },
      { name: "Piotr Stepánovich Verjovenski", desc: "Conspirador manipulador que orquesta el caos revolucionario" },
      { name: "Stepán Trofímovich Verjovenski", desc: "Intelectual liberal de la vieja generación, padre de Piotr" },
      { name: "Iván Shátov", desc: "Exrevolucionario que redescubre la fe rusa y es asesinado por la célula" },
      { name: "Kirílov", desc: "Ingeniero obsesionado con probar la libertad absoluta mediante el suicidio" },
    ],
    relationships: [
      { from: 1, to: 0, type: "manipulacion", label: "usa como líder simbólico" },
      { from: 2, to: 1, type: "familia", label: "padre e hijo" },
      { from: 1, to: 3, type: "rivalidad", label: "ordena asesinato" },
      { from: 0, to: 3, type: "mentor", label: "influencia ideológica" },
      { from: 0, to: 4, type: "mentor", label: "influencia filosófica" },
    ],
  },
  {
    id: "el-adolescente",
    title: "El adolescente",
    titleOrig: "Подросток",
    year: 1875,
    pages: 500,
    chapters: 46,
    themes: ["identidad", "familia", "sociedad"],
    desc: "Un joven hijo ilegítimo busca poder y reconocimiento mientras descifra su relación con un padre ausente.",
    cover: "mirror",
    location: "San Petersburgo, Rusia",
    writtenContext: "Publicada en 1875 en Anales de la Patria, la única novela mayor de Dostoievski que no apareció en El Mensajero Ruso. Escrita tras el éxito de Los demonios, mientras dirigía la revista Diario de un escritor.",
    characters: [
      { name: "Arkadi Makárovich Dolgoruki", desc: "Narrador, joven de 19 años, hijo ilegítimo que busca su identidad" },
      { name: "Andréi Petróvich Versílov", desc: "Padre biológico de Arkadi, noble intelectual y contradictorio" },
      { name: "Sofía Andréievna (Mamá)", desc: "Madre humilde de Arkadi, devota de Versílov" },
      { name: "Katerina Nikoláievna Ajmákova", desc: "Mujer aristocrática de quien Versílov y Arkadi se enamoran" },
      { name: "Makar Ivánovich Dolgoruki", desc: "Marido legal de Sofía, peregrino religioso, figura espiritual" },
    ],
    relationships: [
      { from: 0, to: 1, type: "familia", label: "hijo ilegítimo" },
      { from: 1, to: 2, type: "amor", label: "relación compleja" },
      { from: 2, to: 4, type: "familia", label: "esposa legal" },
      { from: 1, to: 3, type: "amor-no-correspondido", label: "enamorado de" },
      { from: 0, to: 3, type: "amor-no-correspondido", label: "fascinado por" },
    ],
  },
  {
    id: "los-hermanos-karamazov",
    title: "Los hermanos Karamázov",
    titleOrig: "Братья Карамазовы",
    year: 1880,
    pages: 800,
    chapters: 100,
    themes: ["fe", "familia", "crimen", "existencialismo", "redencion"],
    desc: "Tres hermanos enfrentan el parricidio, la fe, la razón y la lujuria en la obra cumbre de Dostoievski.",
    cover: "brothers",
    location: "Skotoprigónevsk (ciudad provinciana ficticia, Rusia)",
    writtenContext: "Última y más ambiciosa novela de Dostoievski, publicada entre 1879-1880 en El Mensajero Ruso. Planeó una segunda parte que nunca escribió: murió en enero de 1881, meses después de completarla.",
    characters: [
      { name: "Dmitri (Mitia) Karamázov", desc: "Hermano mayor, apasionado e impulsivo, acusado de parricidio" },
      { name: "Iván Karamázov", desc: "Hermano intelectual, ateo, autor del poema del Gran Inquisidor" },
      { name: "Alexéi (Aliosha) Karamázov", desc: "Hermano menor, novicio religioso, discípulo del stárets Zósima" },
      { name: "Fiódor Pávlovich Karamázov", desc: "El padre, bufón lujurioso y avaro, víctima del parricidio" },
      { name: "Smerdiákov", desc: "Medio hermano ilegítimo, cocinero epiléptico, ejecutor del crimen" },
      { name: "Stárets Zósima", desc: "Anciano monje, mentor espiritual de Aliosha" },
    ],
    relationships: [
      { from: 0, to: 3, type: "familia", label: "padre e hijo" },
      { from: 1, to: 3, type: "familia", label: "padre e hijo" },
      { from: 2, to: 3, type: "familia", label: "padre e hijo" },
      { from: 4, to: 3, type: "familia", label: "hijo ilegítimo" },
      { from: 4, to: 1, type: "manipulacion", label: "influenciado por" },
      { from: 2, to: 5, type: "mentor", label: "discípulo" },
      { from: 0, to: 1, type: "rivalidad", label: "conflicto fraterno" },
    ],
  },
];
