export const THEMES = {
  existencialismo: { label: "Existencialismo", color: "#8B5CF6" },
  redencion: { label: "Redención", color: "#F59E0B" },
  fe: { label: "Fe y moralidad", color: "#3B82F6" },
  amor: { label: "Amor", color: "#EC4899" },
  sociedad: { label: "Sociedad", color: "#10B981" },
  psicologia: { label: "Psicología", color: "#EF4444" },
  politica: { label: "Política", color: "#6366F1" },
  familia: { label: "Familia", color: "#F97316" },
  identidad: { label: "Identidad", color: "#14B8A6" },
  crimen: { label: "Crimen", color: "#DC2626" },
  soledad: { label: "Soledad", color: "#6B7280" },
  adiccion: { label: "Adicción", color: "#A855F7" },
};

export const NOVELS = [
  {
    id: "pobres-gentes",
    title: "Pobres gentes",
    titleOrig: "Бедные люди",
    year: 1846,
    pages: 180,
    themes: ["amor", "sociedad", "soledad"],
    desc: "Intercambio epistolar entre un funcionario humilde y una joven costurera que revela la dignidad en la pobreza.",
    cover: "letter",
  },
  {
    id: "el-doble",
    title: "El doble",
    titleOrig: "Двойник",
    year: 1846,
    pages: 140,
    themes: ["identidad", "psicologia"],
    desc: "Un burócrata descubre que un doble idéntico invade su vida, precipitándolo hacia la locura.",
    cover: "double",
  },
  {
    id: "noches-blancas",
    title: "Noches blancas",
    titleOrig: "Белые ночи",
    year: 1848,
    pages: 80,
    themes: ["amor", "soledad"],
    desc: "Cuatro noches de encuentro entre un soñador solitario y una joven que espera a su amado en San Petersburgo.",
    cover: "moon",
  },
  {
    id: "humillados-y-ofendidos",
    title: "Humillados y ofendidos",
    titleOrig: "Униженные и оскорблённые",
    year: 1861,
    pages: 350,
    themes: ["sociedad", "amor", "redencion"],
    desc: "Un escritor enfermo narra la destrucción de familias enteras por la crueldad de un aristócrata sin escrúpulos.",
    cover: "broken",
  },
  {
    id: "memorias-del-subsuelo",
    title: "Memorias del subsuelo",
    titleOrig: "Записки из подполья",
    year: 1864,
    pages: 130,
    themes: ["existencialismo", "psicologia", "soledad"],
    desc: "El monólogo frenético de un hombre que rechaza la razón y la sociedad desde su agujero subterráneo.",
    cover: "stairs",
  },
  {
    id: "crimen-y-castigo",
    title: "Crimen y castigo",
    titleOrig: "Преступление и наказание",
    year: 1866,
    pages: 580,
    themes: ["crimen", "redencion", "psicologia", "fe"],
    desc: "Un estudiante asesina a una anciana usuraria convencido de su superioridad moral, pero la culpa lo consume.",
    cover: "axe",
  },
  {
    id: "el-jugador",
    title: "El jugador",
    titleOrig: "Игрок",
    year: 1867,
    pages: 170,
    themes: ["adiccion", "amor", "sociedad"],
    desc: "Un tutor ruso se hunde en la fiebre de la ruleta en un casino alemán, atrapado entre el juego y una mujer.",
    cover: "roulette",
  },
  {
    id: "el-idiota",
    title: "El idiota",
    titleOrig: "Идиот",
    year: 1869,
    pages: 640,
    themes: ["fe", "sociedad", "amor", "psicologia"],
    desc: "El príncipe Myshkin, un hombre de bondad cristiana absoluta, es destruido por la sociedad petersburguesa.",
    cover: "halo",
  },
  {
    id: "el-eterno-marido",
    title: "El eterno marido",
    titleOrig: "Вечный муж",
    year: 1870,
    pages: 160,
    themes: ["psicologia", "identidad"],
    desc: "Un viudo busca al amante de su esposa fallecida en un duelo psicológico de humillación y dependencia.",
    cover: "ring",
  },
  {
    id: "los-demonios",
    title: "Los demonios",
    titleOrig: "Бесы",
    year: 1872,
    pages: 700,
    themes: ["politica", "existencialismo", "crimen"],
    desc: "Una célula revolucionaria nihilista siembra el caos en una ciudad provinciana rusa, destruyendo todo a su paso.",
    cover: "flame",
  },
  {
    id: "el-adolescente",
    title: "El adolescente",
    titleOrig: "Подросток",
    year: 1875,
    pages: 500,
    themes: ["identidad", "familia", "sociedad"],
    desc: "Un joven hijo ilegítimo busca poder y reconocimiento mientras descifra su relación con un padre ausente.",
    cover: "mirror",
  },
  {
    id: "los-hermanos-karamazov",
    title: "Los hermanos Karamázov",
    titleOrig: "Братья Карамазовы",
    year: 1880,
    pages: 800,
    themes: ["fe", "familia", "crimen", "existencialismo", "redencion"],
    desc: "Tres hermanos enfrentan el parricidio, la fe, la razón y la lujuria en la obra cumbre de Dostoievski.",
    cover: "brothers",
  },
];
