export const THEMES = {
  existencialismo: { label: "Existencialismo", color: "#8B5CF6" },
  redencion: { label: "Redención", color: "#F59E0B" },
  fe: { label: "Fe y moralidad", color: "#3B82F6" },
  amor: { label: "Amor", color: "#EC4899" },
  sociedad: { label: "Sociedad", color: "#10B981" },
  psicologia: { label: "Psicología", color: "#EF4444" },
  politica: { label: "Política", color: "#6366F1" },
  familia: { label: "Familia", color: "#F97316" },
  identidad: { label: "Identidad", color: "#14B8A6" },
  crimen: { label: "Crimen", color: "#DC2626" },
  soledad: { label: "Soledad", color: "#6B7280" },
  adiccion: { label: "Adicción", color: "#A855F7" },
};

export const NOVELS = [
  {
    id: "pobres-gentes",
    title: "Pobres gentes",
    titleOrig: "Бедные люди",
    year: 1846,
    pages: 180,
    chapters: 31,
    themes: ["amor", "sociedad", "soledad"],
    desc: "Intercambio epistolar entre un funcionario humilde y una joven costurera que revela la dignidad en la pobreza.",
    cover: "letter",
    location: "San Petersburgo, Rusia",
    writtenContext: "Primera novela de Dostoievski, escrita a los 24 años. Bélinskiy, el crítico más influyente de la época, la elogió diciendo: «¡Ha nacido un nuevo Gógol!». Publicada en 1846 en el Almanaque de Petersburgo.",
    characters: [
      { name: "Makar Dévushkin", desc: "Funcionario copista empobrecido, bondadoso y sentimental" },
      { name: "Várvara Dobrosiólova", desc: "Joven huérfana y costurera, corresponsal de Makar" },
      { name: "Bykov", desc: "Terrateniente adinerado e indiferente que irrumpe en la vida de Várvara" },
      { name: "Pókrovski (hijo)", desc: "Joven estudiante tuberculoso que enseña a Várvara y la enamora" },
      { name: "Anna Fiódorovna", desc: "Prima lejana de Várvara, alcahueta que la explota" },
    ],
    relationships: [
      { from: 0, to: 1, type: "amor-no-correspondido", label: "amor epistolar" },
      { from: 2, to: 1, type: "manipulacion", label: "interés por conveniencia" },
      { from: 1, to: 3, type: "amor", label: "primer amor" },
      { from: 4, to: 1, type: "manipulacion", label: "explota a Várvara" },
      { from: 4, to: 2, type: "amistad", label: "cómplice" },
    ],
  },
  {
    id: "el-doble",
    title: "El doble",
    titleOrig: "Двойник",
    year: 1846,
    pages: 140,
    chapters: 13,
    themes: ["identidad", "psicologia"],
    desc: "Un burócrata descubre que un doble idéntico invade su vida, amenazando su identidad y su cordura.",
    cover: "double",
    location: "San Petersburgo, Rusia",
    writtenContext: "Segunda novela, publicada apenas semanas después de Pobres gentes en 1846. Fue mal recibida por la crítica. Dostoievski la consideraba una de sus ideas más importantes, aunque reconocía que la forma había fallado.",
    characters: [
      { name: "Yákov Petróvich Goliadkin", desc: "Consejero titular inseguro y paranoico, protagonista" },
      { name: "Goliadkin Jr.", desc: "El doble idéntico, astuto y manipulador, que usurpa su vida" },
      { name: "Klara Olsúfievna", desc: "Hija del consejero de Estado, objeto del amor imposible de Goliadkin" },
      { name: "Olsufi Ivánovich", desc: "Consejero de Estado, padre de Klara, antiguo benefactor de Goliadkin" },
      { name: "Krestián Ivánovich Rutenspitz", desc: "Médico alemán de Goliadkin que intenta tratarlo" },
      { name: "Petrushka", desc: "Criado insolente de Goliadkin que lo desprecia abiertamente" },
    ],
    relationships: [
      { from: 0, to: 1, type: "rivalidad", label: "doble usurpador" },
      { from: 0, to: 2, type: "amor-no-correspondido", label: "amor imposible" },
      { from: 1, to: 2, type: "rivalidad", label: "pretende a Klara" },
      { from: 0, to: 3, type: "amor-no-correspondido", label: "busca aprobación" },
      { from: 1, to: 3, type: "manipulacion", label: "gana su favor" },
      { from: 0, to: 4, type: "amistad", label: "paciente" },
      { from: 0, to: 5, type: "familia", label: "amo y criado" },
    ],
  },
  {
    id: "noches-blancas",
    title: "Noches blancas",
    titleOrig: "Белые ночи",
    year: 1848,
    pages: 80,
    chapters: 6,
    themes: ["amor", "soledad"],
    desc: "Cuatro noches de encuentro entre un soñador solitario y una joven que espera a su amado en San Petersburgo.",
    cover: "moon",
    location: "San Petersburgo, Rusia",
    writtenContext: "Escrita en 1848, poco antes del arresto de Dostoievski por participar en el círculo Petrashevski. Ambientada durante las célebres noches blancas de San Petersburgo, cuando el sol apenas se oculta.",
    characters: [
      { name: "El Soñador", desc: "Narrador anónimo, joven solitario e idealista que vive en sus fantasías" },
      { name: "Nástenka", desc: "Joven vivaz que espera el regreso de su amado junto al canal" },
      { name: "El inquilino", desc: "Joven de quien Nástenka está enamorada, ausente durante la historia" },
      { name: "La Abuela", desc: "Abuela ciega de Nástenka que la tiene atada con un alfiler a su falda" },
    ],
    relationships: [
      { from: 0, to: 1, type: "amor-no-correspondido", label: "se enamora de" },
      { from: 1, to: 2, type: "amor", label: "amado ausente" },
      { from: 3, to: 1, type: "familia", label: "abuela protectora" },
    ],
  },
  {
    id: "humillados-y-ofendidos",
    title: "Humillados y ofendidos",
    titleOrig: "Униженные и оскорблённые",
    year: 1861,
    pages: 350,
    chapters: 45,
    themes: ["sociedad", "amor", "redencion"],
    desc: "Un escritor enfermo narra la destrucción de familias enteras por la crueldad de un aristócrata sin escrúpulos.",
    cover: "broken",
    location: "San Petersburgo, Rusia",
    writtenContext: "Primera novela tras regresar del exilio en Siberia (1849-1859). Publicada por entregas en la revista Tiempo, que Dostoievski cofundó con su hermano Mijaíl. Marca su regreso a la vida literaria petersburguesa.",
    characters: [
      { name: "Iván Petróvich", desc: "Escritor y narrador, enamorado de Natasha" },
      { name: "Natasha Ihmenieva", desc: "Joven que abandona a su familia por amor a Aliosha" },
      { name: "Príncipe Valkovski", desc: "Aristócrata cínico y despiadado, antagonista principal" },
      { name: "Aliosha (Alexéi)", desc: "Hijo del príncipe, ingenuo y voluble en sus afectos" },
      { name: "Nelly", desc: "Niña huérfana y enferma, víctima de la crueldad de Valkovski" },
      { name: "Nikolái Ijméniev", desc: "Padre de Natasha, antiguo administrador de Valkovski, destrozado por la deshonra" },
      { name: "Anna Andréievna Ijménieva", desc: "Madre de Natasha, devota y sufriente" },
      { name: "Katia", desc: "Joven condesa heredera, rival inocente de Natasha por el amor de Aliosha" },
      { name: "Maslobóiev", desc: "Antiguo compañero de Iván, detective informal que investiga el pasado de Nelly" },
    ],
    relationships: [
      { from: 0, to: 1, type: "amor-no-correspondido", label: "enamorado de" },
      { from: 1, to: 3, type: "amor", label: "abandona familia por" },
      { from: 2, to: 3, type: "familia", label: "padre e hijo" },
      { from: 2, to: 4, type: "manipulacion", label: "victimario" },
      { from: 2, to: 1, type: "manipulacion", label: "intenta separar" },
      { from: 5, to: 1, type: "familia", label: "padre e hija" },
      { from: 6, to: 1, type: "familia", label: "madre e hija" },
      { from: 5, to: 2, type: "rivalidad", label: "enemigo por deshonra" },
      { from: 3, to: 7, type: "amor", label: "se enamora de" },
      { from: 7, to: 1, type: "rivalidad", label: "rival involuntaria" },
      { from: 8, to: 0, type: "amistad", label: "antiguo compañero" },
      { from: 8, to: 4, type: "protector", label: "investiga su origen" },
    ],
  },
  {
    id: "memorias-del-subsuelo",
    title: "Memorias del subsuelo",
    titleOrig: "Записки из подполья",
    year: 1864,
    pages: 130,
    chapters: 11,
    themes: ["existencialismo", "psicologia", "soledad"],
    desc: "El monólogo frenético de un hombre que rechaza la razón y la sociedad desde su agujero subterráneo.",
    cover: "stairs",
    location: "San Petersburgo, Rusia",
    writtenContext: "Escrita en 1864, año trágico para Dostoievski: murieron su esposa María y su hermano Mijaíl. Considerada precursora del existencialismo, fue una respuesta directa al racionalismo utópico de Chernishevski.",
    characters: [
      { name: "El Hombre del Subsuelo", desc: "Narrador anónimo, exfuncionario amargado y contradictorio de 40 años" },
      { name: "Liza", desc: "Joven prostituta que el narrador encuentra una noche y con quien entabla una relación ambigua" },
      { name: "Zvérkov", desc: "Antiguo compañero de escuela, exitoso y arrogante, objeto de la envidia del narrador" },
      { name: "Simónov", desc: "Antiguo compañero de escuela, el único que tolera al narrador" },
      { name: "Apollon", desc: "Criado altanero del narrador que lo humilla con su indiferencia" },
    ],
    relationships: [
      { from: 0, to: 1, type: "manipulacion", label: "relación ambigua" },
      { from: 0, to: 2, type: "rivalidad", label: "envidia y resentimiento" },
      { from: 0, to: 3, type: "amistad", label: "relación tensa" },
      { from: 3, to: 2, type: "amistad", label: "amigo de Zvérkov" },
      { from: 0, to: 4, type: "rivalidad", label: "guerra doméstica" },
    ],
  },
  {
    id: "crimen-y-castigo",
    title: "Crimen y castigo",
    titleOrig: "Преступление и наказание",
    year: 1866,
    pages: 580,
    chapters: 42,
    themes: ["crimen", "redencion", "psicologia", "fe"],
    desc: "Un estudiante asesina a una anciana usuraria convencido de su superioridad moral, pero la culpa lo consume.",
    cover: "axe",
    location: "San Petersburgo, Rusia",
    writtenContext: "Escrita entre 1865-1866, publicada por entregas en El Mensajero Ruso. Dostoievski la escribió bajo enorme presión económica, agobiado por deudas de juego y las de la revista de su difunto hermano.",
    characters: [
      { name: "Rodión Raskólnikov", desc: "Estudiante empobrecido obsesionado con una teoría sobre los hombres extraordinarios" },
      { name: "Sonia Marmeládova", desc: "Joven que se sacrifica por su familia, guía moral de Raskólnikov" },
      { name: "Porfirio Petróvich", desc: "Juez de instrucción astuto que investiga el crimen" },
      { name: "Dunia Raskólnikova", desc: "Hermana de Rodión, fuerte e independiente" },
      { name: "Svidrigáilov", desc: "Terrateniente corrupto y nihilista obsesionado con Dunia" },
      { name: "Razumijin", desc: "Mejor amigo de Raskólnikov, estudiante leal y enérgico" },
      { name: "Marmeládov", desc: "Padre de Sonia, funcionario cesante consumido por el alcohol" },
      { name: "Katerina Ivánovna", desc: "Madrastra de Sonia, viuda tuberculosa, orgullosa y desesperada" },
      { name: "Luzhin", desc: "Abogado mezquino y vanidoso, prometido rechazado de Dunia" },
      { name: "Pulqueria Raskólnikova", desc: "Madre de Rodión y Dunia, abnegada y temerosa" },
      { name: "Aliona Ivánovna", desc: "Vieja prestamista usurera, antagonista silenciosa" },
      { name: "Lebeziátnikov", desc: "Joven inquilino progresista, compañero de pensión de Luzhin" },
    ],
    relationships: [
      { from: 0, to: 1, type: "amor", label: "vínculo espiritual" },
      { from: 0, to: 3, type: "familia", label: "hermanos" },
      { from: 2, to: 0, type: "investigacion", label: "investiga" },
      { from: 4, to: 3, type: "amor-no-correspondido", label: "obsesión" },
      { from: 4, to: 0, type: "rivalidad", label: "doble oscuro" },
      { from: 5, to: 0, type: "amistad", label: "mejor amigo" },
      { from: 5, to: 3, type: "amor", label: "se enamoran" },
      { from: 6, to: 1, type: "familia", label: "padre e hija" },
      { from: 7, to: 1, type: "familia", label: "madrastra" },
      { from: 6, to: 7, type: "familia", label: "esposos" },
      { from: 8, to: 3, type: "manipulacion", label: "prometido rechazado" },
      { from: 9, to: 0, type: "familia", label: "madre" },
      { from: 9, to: 3, type: "familia", label: "madre" },
      { from: 0, to: 10, type: "rivalidad", label: "deudor resentido" },
      { from: 11, to: 8, type: "amistad", label: "compañero de pensión" },
    ],
  },
  {
    id: "el-jugador",
    title: "El jugador",
    titleOrig: "Игрок",
    year: 1867,
    pages: 170,
    chapters: 17,
    themes: ["adiccion", "amor", "sociedad"],
    desc: "Un tutor ruso se hunde en la fiebre de la ruleta en un casino alemán, atrapado entre el juego y una mujer.",
    cover: "roulette",
    location: "Roulettenburg (ciudad ficticia alemana, inspirada en Wiesbaden y Bad Homburg)",
    writtenContext: "Dictada en solo 26 días a la taquígrafa Anna Grigórievna Snítkina (su futura segunda esposa) para cumplir un contrato editorial leonino. Basada en su propia adicción al juego en los casinos europeos.",
    characters: [
      { name: "Alexéi Ivánovich", desc: "Tutor ruso, narrador, atrapado por la adicción al juego" },
      { name: "Polina", desc: "Hijastra del General, mujer orgullosa de quien Alexéi está enamorado" },
      { name: "El General", desc: "Militar retirado endeudado que espera la herencia de su tía" },
      { name: "La Abuelita (Antonida Vasílievna)", desc: "Anciana rica y enérgica cuya llegada inesperada trastorna los planes de todos" },
      { name: "Mr. Astley", desc: "Inglés reservado y honorable, enamorado en secreto de Polina" },
      { name: "Mademoiselle Blanche", desc: "Aventurera francesa que seduce al General por su dinero" },
      { name: "Des Grieux", desc: "Marqués francés, acreedor del General y pretendiente calculador de Polina" },
    ],
    relationships: [
      { from: 0, to: 1, type: "amor-no-correspondido", label: "enamorado de" },
      { from: 2, to: 1, type: "familia", label: "padrastro" },
      { from: 2, to: 3, type: "familia", label: "espera herencia" },
      { from: 4, to: 1, type: "amor-no-correspondido", label: "amor secreto" },
      { from: 5, to: 2, type: "manipulacion", label: "lo seduce por dinero" },
      { from: 6, to: 1, type: "amor-no-correspondido", label: "pretende a Polina" },
      { from: 6, to: 2, type: "manipulacion", label: "acreedor" },
      { from: 0, to: 5, type: "rivalidad", label: "desprecio mutuo" },
    ],
  },
  {
    id: "el-idiota",
    title: "El idiota",
    titleOrig: "Идиот",
    year: 1869,
    pages: 640,
    chapters: 44,
    themes: ["fe", "sociedad", "amor", "psicologia"],
    desc: "El príncipe Myshkin, un hombre de bondad cristiana absoluta, se enfrenta a la sociedad petersburguesa.",
    cover: "halo",
    location: "San Petersburgo y Pávlovsk, Rusia (con prólogo en Suiza)",
    writtenContext: "Escrita entre 1867-1869 durante el primer viaje al extranjero de Dostoievski con su esposa Anna. Compuesta entre Ginebra, Vevey, Milán y Florencia, mientras el matrimonio vivía en la pobreza.",
    characters: [
      { name: "Príncipe Lev Myshkin", desc: "Hombre de bondad pura, epiléptico, recién regresado de un sanatorio suizo" },
      { name: "Nastasia Filíppovna", desc: "Mujer de belleza trágica, atormentada por su pasado de abuso" },
      { name: "Parfión Rogozhin", desc: "Hijo de comerciante, apasionado y violento, obsesionado con Nastasia" },
      { name: "Aglaya Yepánchina", desc: "Joven inteligente y orgullosa, enamorada del príncipe" },
      { name: "Gania Ivolguin", desc: "Secretario ambicioso que busca casarse por dinero" },
      { name: "General Yepanchin", desc: "Padre de Aglaya, general adinerado y admirador de Nastasia" },
      { name: "Lizaveta Prokófievna Yepánchina", desc: "Madre de Aglaya, mujer impetuosa y de buen corazón" },
      { name: "Ippolit Teréntiev", desc: "Joven tísico de 18 años que desafía la bondad del príncipe" },
      { name: "Totski (Afanasi Ivánovich)", desc: "Rico terrateniente que abusó de Nastasia en su infancia" },
      { name: "Lebedev", desc: "Funcionario astuto y bufón, intermediario y comentarista del Apocalipsis" },
    ],
    relationships: [
      { from: 0, to: 1, type: "amor", label: "compasión y amor" },
      { from: 0, to: 3, type: "amor", label: "amor puro" },
      { from: 2, to: 1, type: "amor", label: "obsesión posesiva" },
      { from: 2, to: 0, type: "rivalidad", label: "rival y hermano jurado" },
      { from: 4, to: 1, type: "manipulacion", label: "pretende por dinero" },
      { from: 5, to: 3, type: "familia", label: "padre e hija" },
      { from: 6, to: 3, type: "familia", label: "madre e hija" },
      { from: 5, to: 1, type: "amor-no-correspondido", label: "admiración culpable" },
      { from: 7, to: 0, type: "rivalidad", label: "desafía su bondad" },
      { from: 8, to: 1, type: "manipulacion", label: "abusó en su infancia" },
      { from: 9, to: 0, type: "amistad", label: "anfitrión intrigante" },
    ],
  },
  {
    id: "el-eterno-marido",
    title: "El eterno marido",
    titleOrig: "Вечный муж",
    year: 1870,
    pages: 160,
    chapters: 17,
    themes: ["psicologia", "identidad"],
    desc: "Un viudo busca al amante de su esposa fallecida en un duelo psicológico de humillación y dependencia.",
    cover: "ring",
    location: "San Petersburgo, Rusia",
    writtenContext: "Novela corta escrita en 1870, durante el período más productivo de Dostoievski en el extranjero. Publicada en la revista Aurora. Una de sus obras más concentradas y psicológicamente incisivas.",
    characters: [
      { name: "Pável Pávlovich Trúsotski", desc: "Viudo sumiso que busca al amante de su difunta esposa" },
      { name: "Alexéi Ivánovich Velchanínov", desc: "Ex amante elegante y ocioso, atormentado por la culpa" },
      { name: "Liza", desc: "Hija pequeña de la difunta esposa de Trúsotski, cuya paternidad es ambigua" },
      { name: "Natalia Vasílievna", desc: "Difunta esposa de Trúsotski, centro ausente de la trama" },
      { name: "Nadiezhda Zajlébinina", desc: "Joven a quien Trúsotski corteja como nueva esposa" },
    ],
    relationships: [
      { from: 0, to: 1, type: "rivalidad", label: "busca al amante" },
      { from: 1, to: 2, type: "familia", label: "vínculo con Liza" },
      { from: 0, to: 2, type: "familia", label: "padre legal" },
      { from: 0, to: 3, type: "familia", label: "esposo de la difunta" },
      { from: 1, to: 3, type: "amor", label: "amante" },
      { from: 0, to: 4, type: "amor-no-correspondido", label: "corteja" },
      { from: 1, to: 4, type: "protector", label: "la previene" },
    ],
  },
  {
    id: "los-demonios",
    title: "Los demonios",
    titleOrig: "Бесы",
    year: 1872,
    pages: 700,
    chapters: 38,
    themes: ["politica", "existencialismo", "crimen"],
    desc: "Una célula revolucionaria nihilista siembra el caos en una ciudad provinciana rusa, destruyendo todo a su paso.",
    cover: "flame",
    location: "Ciudad provinciana ficticia, Rusia",
    writtenContext: "Inspirada en el caso real de Necháiev, revolucionario que ordenó el asesinato de un miembro de su propia célula en 1869. Dostoievski la escribió como advertencia profética contra el nihilismo radical.",
    characters: [
      { name: "Nikolái Stavroguin", desc: "Carismático y enigmático, centro moral vacío de la novela" },
      { name: "Piotr Stepánovich Verjovenski", desc: "Conspirador manipulador que orquesta el caos revolucionario" },
      { name: "Stepán Trofímovich Verjovenski", desc: "Intelectual liberal de la vieja generación, padre de Piotr" },
      { name: "Iván Shátov", desc: "Exrevolucionario que redescubre la fe rusa, en conflicto con la célula" },
      { name: "Kirílov", desc: "Ingeniero obsesionado con una idea filosófica extrema sobre la libertad absoluta" },
      { name: "Varvara Petrovna Stavróguina", desc: "Madre de Stavroguin, mujer orgullosa y dominante, protectora de Stepán" },
      { name: "María Timoféievna Lebiádkina", desc: "La Coja, esposa secreta de Stavroguin, inocente y demente" },
      { name: "Capitán Lebiádkin", desc: "Hermano de María, borracho bufón que extorsiona a Stavroguin" },
      { name: "Liza Tushina", desc: "Joven aristocrática enamorada de Stavroguin" },
      { name: "Dasha Shátova", desc: "Hermana de Shátov, protegida de Varvara Petrovna" },
      { name: "Fedka el Presidiario", desc: "Exconvicto usado como instrumento por Piotr" },
    ],
    relationships: [
      { from: 1, to: 0, type: "manipulacion", label: "usa como líder simbólico" },
      { from: 2, to: 1, type: "familia", label: "padre e hijo" },
      { from: 1, to: 3, type: "rivalidad", label: "ve como amenaza" },
      { from: 0, to: 3, type: "mentor", label: "influencia ideológica" },
      { from: 0, to: 4, type: "mentor", label: "influencia filosófica" },
      { from: 5, to: 0, type: "familia", label: "madre e hijo" },
      { from: 5, to: 2, type: "protector", label: "mecenas y amiga" },
      { from: 0, to: 6, type: "familia", label: "esposo secreto" },
      { from: 7, to: 0, type: "manipulacion", label: "extorsiona" },
      { from: 7, to: 6, type: "familia", label: "hermanos" },
      { from: 8, to: 0, type: "amor", label: "enamorada de" },
      { from: 1, to: 10, type: "manipulacion", label: "usa como instrumento" },
      { from: 9, to: 3, type: "familia", label: "hermana" },
      { from: 0, to: 9, type: "manipulacion", label: "relación impuesta" },
    ],
  },
  {
    id: "el-adolescente",
    title: "El adolescente",
    titleOrig: "Подросток",
    year: 1875,
    pages: 500,
    chapters: 46,
    themes: ["identidad", "familia", "sociedad"],
    desc: "Un joven hijo ilegítimo busca poder y reconocimiento mientras descifra su relación con un padre ausente.",
    cover: "mirror",
    location: "San Petersburgo, Rusia",
    writtenContext: "Publicada en 1875 en Anales de la Patria, la única novela mayor de Dostoievski que no apareció en El Mensajero Ruso. Escrita tras el éxito de Los demonios, mientras dirigía la revista Diario de un escritor.",
    characters: [
      { name: "Arkadi Makárovich Dolgoruki", desc: "Narrador, joven de 19 años, hijo ilegítimo que busca su identidad" },
      { name: "Andréi Petróvich Versílov", desc: "Padre biológico de Arkadi, noble intelectual y contradictorio" },
      { name: "Sofía Andréievna (Mamá)", desc: "Madre humilde de Arkadi, devota de Versílov" },
      { name: "Katerina Nikoláievna Ajmákova", desc: "Mujer aristocrática de quien Versílov y Arkadi se enamoran" },
      { name: "Makar Ivánovich Dolgoruki", desc: "Marido legal de Sofía, peregrino religioso, figura espiritual" },
      { name: "Liza Versílova", desc: "Hermana legítima de Arkadi por parte de Versílov" },
      { name: "Príncipe Serguéi Sokolski", desc: "Joven príncipe amigo de Arkadi, implicado en intrigas" },
      { name: "Lambert", desc: "Antiguo compañero de colegio de Arkadi, estafador y chantajista" },
    ],
    relationships: [
      { from: 0, to: 1, type: "familia", label: "hijo ilegítimo" },
      { from: 1, to: 2, type: "amor", label: "relación compleja" },
      { from: 2, to: 4, type: "familia", label: "esposa legal" },
      { from: 1, to: 3, type: "amor-no-correspondido", label: "enamorado de" },
      { from: 0, to: 3, type: "amor-no-correspondido", label: "fascinado por" },
      { from: 5, to: 1, type: "familia", label: "hija legítima" },
      { from: 0, to: 5, type: "familia", label: "medio hermanos" },
      { from: 0, to: 6, type: "amistad", label: "amigos" },
      { from: 7, to: 0, type: "manipulacion", label: "intenta corromperlo" },
      { from: 7, to: 3, type: "manipulacion", label: "quiere chantajear" },
    ],
  },
  {
    id: "los-hermanos-karamazov",
    title: "Los hermanos Karamázov",
    titleOrig: "Братья Карамазовы",
    year: 1880,
    pages: 800,
    chapters: 100,
    themes: ["fe", "familia", "crimen", "existencialismo", "redencion"],
    desc: "Tres hermanos enfrentan el parricidio, la fe, la razón y la lujuria en la obra cumbre de Dostoievski.",
    cover: "brothers",
    location: "Skotoprigónevsk (ciudad provinciana ficticia, Rusia)",
    writtenContext: "Última y más ambiciosa novela de Dostoievski, publicada entre 1879-1880 en El Mensajero Ruso. Planeó una segunda parte que nunca escribió: murió en enero de 1881, meses después de completarla.",
    characters: [
      { name: "Dmitri (Mitia) Karamázov", desc: "Hermano mayor, apasionado e impulsivo, en conflicto abierto con su padre" },
      { name: "Iván Karamázov", desc: "Hermano intelectual, ateo, autor del poema del Gran Inquisidor" },
      { name: "Alexéi (Aliosha) Karamázov", desc: "Hermano menor, novicio religioso, discípulo del stárets Zósima" },
      { name: "Fiódor Pávlovich Karamázov", desc: "El padre, bufón lujurioso y avaro, despreciado por sus hijos" },
      { name: "Smerdiákov", desc: "Medio hermano ilegítimo, cocinero epiléptico, figura enigmática y siniestra" },
      { name: "Stárets Zósima", desc: "Anciano monje, mentor espiritual de Aliosha" },
      { name: "Grúshenka (Agrafena Svétlova)", desc: "Mujer seductora disputada entre Dmitri y Fiódor" },
      { name: "Katerina Ivánovna Verjóvtseva", desc: "Prometida orgullosa de Dmitri que oscila entre él e Iván" },
      { name: "Rakitin", desc: "Seminarista oportunista y cínico, conocido de Aliosha" },
      { name: "Líse Jojlakova", desc: "Joven inválida enamorada de Aliosha" },
      { name: "Kolya Krasotkin", desc: "Muchacho audaz, líder de los niños del pueblo" },
      { name: "Ilusha Sneguiriov", desc: "Niño enfermo defendido por Aliosha y los muchachos" },
      { name: "Capitán Sneguiriov", desc: "Padre humillado de Ilusha, hombre miserable y orgulloso" },
    ],
    relationships: [
      { from: 0, to: 3, type: "familia", label: "padre e hijo" },
      { from: 1, to: 3, type: "familia", label: "padre e hijo" },
      { from: 2, to: 3, type: "familia", label: "padre e hijo" },
      { from: 4, to: 3, type: "familia", label: "hijo ilegítimo" },
      { from: 4, to: 1, type: "manipulacion", label: "influenciado por" },
      { from: 2, to: 5, type: "mentor", label: "discípulo" },
      { from: 0, to: 1, type: "rivalidad", label: "conflicto fraterno" },
      { from: 0, to: 6, type: "amor", label: "pasión" },
      { from: 3, to: 6, type: "rivalidad", label: "rival por Grúshenka" },
      { from: 0, to: 7, type: "amor", label: "prometidos" },
      { from: 7, to: 1, type: "amor-no-correspondido", label: "atracción secreta" },
      { from: 2, to: 11, type: "protector", label: "protege a los niños" },
      { from: 11, to: 12, type: "familia", label: "padre e hijo" },
      { from: 0, to: 12, type: "rivalidad", label: "humilla públicamente" },
      { from: 10, to: 11, type: "amistad", label: "amigos" },
      { from: 6, to: 2, type: "amistad", label: "amistad y fe" },
      { from: 8, to: 2, type: "rivalidad", label: "envidia disfrazada" },
      { from: 2, to: 9, type: "amor", label: "cariño mutuo" },
    ],
  },
];
